export const options = [
  { value: 'masculino', label: 'masculino' },
  { value: 'femenino', label: 'femenino' },
  // ... Otras opciones comunes
];

export const departamentos = [
  { value: '1', label: 'CALIDAD' },
  { value: '2', label: 'CRUM' },
  { value: '3', label: 'EL_SALTO' },
  { value: '4', label: 'C4_GOMEZ_PALACIO' },
  { value: '5', label: 'C4_SANTIAGO_PAPASQUIARO' },
  { value: '6', label: 'ADMINISTRATIVO' },
  { value: '7', label: 'CARTOGRAFIA' },
  { value: '8', label: 'PSICOLOGIA' },
  { value: '9', label: 'S_T_E_911' },
  { value: '10', label: 'SDA_089' },
  { value: '11', label: 'SISTEMAS_Y_DESARROLLO' },
  { value: '12', label: 'TECNICO' },
  { value: '13', label: 'TELECOMUNICACIONES' },
  { value: '14', label: 'VIDEO_VIGILANCIA' },
  { value: '15', label: 'DIRECCION_C5' },
  { value: '16', label: 'AREA_DE_DIAGNOSTICO_DE_PROCESOS' },
  { value: '17', label: 'AREA_JURIDICA' },
  { value: '18', label: 'AREA_LINEA_AMARILLA' },
  { value: '19', label: 'DEPARTAMENTO_ESPACHO' },
  { value: '20', label: 'DEPARTAMENTO_DE_INVESTIGACION_Y_ANALISIS' },
  { value: '21', label: 'DEPARTAMENTO_TELEFONIA_Y_RED_DE_TRANSPORTE' },
  { value: '22', label: 'PERSONAL_SIN_IDENTIFICAR_LUGAR_FISICO' },
  { value: '23', label: 'PROGRAMA_ESMERALDA' },
  { value: '24', label: 'VIGILANCIA_INTERNA' }
];



export const estadoCivil = [
{ value: '1', label: 'casado' },
{ value: '2', label: 'divorciado' },
{ value: '3', label: 'no_aplica' },
{ value: '4', label: 'se_ignora' },
{ value: '5', label: 'separado' },
{ value: '6', label: 'soltero' },
{ value: '7', label: 'union_libre' },
{ value: '8', label: 'viudo' }
];


export const escolaridad = [
  { value: '1', label: 'no_aplica' },
  { value: '2', label: 'preescolar' },
  { value: '3', label: 'primaria' },
  { value: '4', label: 'secundaria' },
  { value: '5', label: 'tecnico_con_secundaria' },
  { value: '6', label: 'preparatoria_bachillerato' },
  { value: '7', label: 'tecnico_con_preparatoria' },
  { value: '8', label: 'profesional' },
  { value: '9', label: 'maestria_doctorado' }
];

export const roles = [ 
  { value: 'estandar', label: 'estandar' },
  { value: 'administrador', label: 'administrador' },
  { value: 'requisicion', label: 'requisicion' },
]

export const cargo = [
  { value: "Subdirector general operativo", label: "Subdirector general operativo" },
  { value: "Jefe de departamento de auditorio", label: "Jefe de departamento de auditorio" },
  { value: "Jefe de turno de auditorio", label: "Jefe de turno de auditorio" },
  { value: "Jefe de departamento CRUM", label: "Jefe de departamento CRUM" },
  { value: "Despachador Crum", label: "Despachador Crum" },
  { value: "Jefe de departamento S.T.E 9-1-1", label: "Jefe de departamento S.T.E 9-1-1" },
  { value: "Jefe de turno S.T.E 9-1-1", label: "Jefe de turno S.T.E 9-1-1" },
  { value: "Operador S.T.E 9-1-1", label: "Operador S.T.E 9-1-1" },
  { value: "Jefe de departamento de calidad", label: "Jefe de departamento de calidad" },
  { value: "Jefe de area de calidad en procesos de acreditacion", label: "Jefe de area de calidad en procesos de acreditacion" },
  { value: "Jefe de area de calidad en procesos de operativos", label: "Jefe de area de calidad en procesos de operativos" },
  { value: "auxiliar en procesos acreditacion", label: "auxiliar en procesos acreditacion" },
  { value: "auxiliar en procesos operativos", label: "auxiliar en procesos operativos" },
  { value: "Jefe de departamento S.D.A 0-8-9", label: "Jefe de departamento S.D.A 0-8-9" },
  { value: "Jefe de turno S.D.A 0-8-9", label: "Jefe de turno S.D.A 0-8-9" },
  { value: "Operador de S.D.A 0-8-9", label: "Operador de S.D.A 0-8-9" },
  { value: "Jefe de departamento de video vigilancia", label: "Jefe de departamento de video vigilancia" },
  { value: "Jefe de turno de video vigilancia", label: "Jefe de turno de video vigilancia" },
  { value: "Auxiliar del departamento video vigilancia", label: "Auxiliar del departamento video vigilancia" },
  { value: "Operador del departamento video vigilancia", label: "Operador del departamento video vigilancia" },
  { value: "Jefe de area tecnica", label: "Jefe de area tecnica" },
  { value: "Tecnico de video vigilancia", label: "Tecnico de video vigilancia" },
  { value: "Jefe de departamento de telecomunicaciones", label: "Jefe de departamento de telecomunicaciones" },
  { value: "Auxiliar de telecomunicaciones", label: "Auxiliar de telecomunicaciones" },
  { value: "Jefe de area Radiocomunicacion", label: "Jefe de area Radiocomunicacion" },
  { value: "Tecnico de Radiocomunicacion", label: "Tecnico de Radiocomunicacion" },
  { value: "Jefe de departamento de telefonia y red de trasporte", label: "Jefe de departamento de telefonia y red de trasporte" },
  { value: "Jefe de area de telefonia", label: "Jefe de area de telefonia" },
  { value: "Jefe de area de red de trasporte", label: "Jefe de area de red de trasporte" },
  { value: "Tecnico de red de telefonia", label: "Tecnico de red de telefonia" },
  { value: "Tecnico de red de trasporte", label: "Tecnico de red de trasporte" },
  { value: "Jefe de departamento de sistemas", label: "Jefe de departamento de sistemas" },
  { value: "Jefe de area de desarrollo", label: "Jefe de area de desarrollo" },
  { value: "Desarrollo web movil", label: "Desarrollo web movil" },
  { value: "Jefe de area de soporte", label: "Jefe de area de soporte" },
  { value: "Tecnico de base de datos", label: "Tecnico de base de datos" },
  { value: "Auxiliar Soporte", label: "Auxiliar Soporte" },
  { value: "Jefe de departamento de cartografia", label: "Jefe de departamento de cartografia" },
  { value: "Jefe de area de geoestadistica", label: "Jefe de area de geoestadistica" },
  { value: "Auxiliar de geoestadistica", label: "Auxiliar de geoestadistica" },
  { value: "Jefe de area de digitalacion", label: "Jefe de area de digitalacion" },
  { value: "Auxiliar de digitalacion", label: "Auxiliar de digitalacion" },
  { value: "Jefe de area de campo", label: "Jefe de area de campo" },
  { value: "Auxiliar de campo", label: "Auxiliar de campo" },
  { value: "Jefe de departamento de psicologia", label: "Jefe de departamento de psicologia" },
  { value: "Auxiliar Administrativo de psicologia", label: "Auxiliar Administrativo de psicologia" },
  { value: "Jefe de area de atencion psicologica", label: "Jefe de area de atencion psicologica" },
  { value: "Auxiliar de psicologica", label: "Auxiliar de psicologica" },
  { value: "Jefe de area de difusion de servicios de C5", label: "Jefe de area de difusion de servicios de C5" },
  { value: "Auxiliar difusion y proximidad", label: "Auxiliar difusion y proximidad" },
  { value: "Jefe de departamento administrativo", label: "Jefe de departamento administrativo" },
  { value: "Auxiliar administrativo", label: "Auxiliar administrativo" },
  { value: "Jefe de area de recursos humanos", label: "Jefe de area de recursos humanos" },
  { value: "Auxiliar RH", label: "Auxiliar RH" },
  { value: "Mensajeria", label: "Mensajeria" },
  { value: "Jefe de area de servicios generales y recursos materiales", label: "Jefe de area de servicios generales y recursos materiales" },
  { value: "Intendencia", label: "Intendencia" },
  { value: "Auxiliar de mantenimiento", label: "Auxiliar de mantenimiento" },
  { value: "Jefe de area de inventarios", label: "Jefe de area de inventarios" },
  { value: "Auxiliar de inventarios", label: "Auxiliar de inventarios" },
  { value: "Jefe de departamento juridico", label: "Jefe de departamento juridico" },
  { value: "Auxiliar juridico", label: "Auxiliar juridico" },
];
